version: '3.8'
services:
  app:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory
      - JWT_SECRET=your_jwt_secret_key
      - EMAIL_USER=your_email@example.com
      - EMAIL_PASS=your_email_password
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
